name: 📢 Broadcast

on:
    workflow_run:
        workflows:
            - '📦 Publish to npm'
        types:
            - completed

jobs:
    on-success:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - run: echo 'The triggering workflow passed'
    on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - run: echo 'The triggering workflow failed'

    broadcast-to-playground:
        runs-on: ubuntu-latest
        needs: on-success
        steps:
            - name: Trigger workflow in another repo
              env:
                  PAT: ${{ secrets.Token_Sync }}
              run: |
                  curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer $PAT" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/cofficlab/JuiceEditor-Playground/actions/workflows/update.yml/dispatches \
                    -d '{"ref":"main"}'

    broadcast-to-examples:
        runs-on: ubuntu-latest
        needs: on-success
        steps:
            - name: Trigger workflow in another repo
              env:
                  PAT: ${{ secrets.Token_Sync }}
              run: |
                  curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer $PAT" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/cofficlab/JuiceEditor-Examples/actions/workflows/update.yml/dispatches \
                    -d '{"ref":"main"}'
