name: Remove old artifacts

on:
  push:
    branches: [main]
    tags:
      - '*'
  schedule:
    # Every day at 9am ...
    - cron: '10 * * * *'
permissions:
  contents: write

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '7 days' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5