---
name: 🧪 Test

on:
    push:
        branches: [dev]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - run: |
                  npm -v
                  npm i -g pnpm
                  pnpm i
                  npm test

    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - run: |
                  npm -v
                  npm i -g pnpm
                  pnpm i --prod
                  npm run build
